export const GET_ADDRESS_REQUEST = "GET_ADDRESS_REQUEST";
export const GET_ADDRESS_SUCCESS = "GET_ADDRESS_SUCCESS";
export const GET_ADDRESS_ERROR = "GET_ADDRESS_ERROR";

export const ADD_To_WishList_SUCCESS = "ADD_To_Cart_SUCCESS";

// export const DELETE_ADDRESS_REQUEST = "DELETE_ADDRESS_REQUEST";
// export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS";
// export const DELETE_ADDRESS_ERROR = "DELETE_ADDRESS_ERROR";